// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
)

type CreateJobListingInput struct {
	Title       string          `json:"title"`
	Description string          `json:"description"`
	Company     string          `json:"company"`
	URL         string          `json:"url"`
	Image       *graphql.Upload `json:"image"`
}

type DeleteJobResponse struct {
	DeleteJobID string `json:"deleteJobId"`
}

type JobListing struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Company     string `json:"company"`
	URL         string `json:"url"`
	Image       string `json:"image"`
}

type UpdateJobListingInput struct {
	Title       *string         `json:"title"`
	Description *string         `json:"description"`
	Company     *string         `json:"company"`
	URL         *string         `json:"url"`
	Image       *graphql.Upload `json:"image"`
}
